### ISSUE TITLE
Is this a feature-complete port of Slim?

### ISSUE THREAD

**Issue by chriscoyier** [slm-lang/slm#40]
This isn't a bug, so feel free to close, I'm just curious.

Does this support the entire syntax of http://slim-lang.com/ ? Or are there compilation differences?

**Comment by yury** [comment]
Almost complete :)

1. Doesn't support [splat attributes](https://github.com/slim-template/slim#splat-attributes-). I wanted to keep compiler as small as possible
2. Doesn't support pretty output. Also to keep library small
3. Use `${}` js interpolation not ruby `#{}`
4. Only supports `(...)`, `[...]` as attributes wrappers (skip `{}`)
5. For verbatim  text with trailing space use `.` instead of `\``. Just decided is cleaner that way.
6. Added `extend`, `partial`, `content`, `mixin`, `j` building functions.

**Comment by chriscoyier** [comment]
Thanks for the info!
